### ISSUE TITLE
install failed on laravel 6.0.4

### ISSUE THREAD

**Issue by olipiskandar** [Mckenziearts/laravel-oauth#5]
i got error :
- Conclusion: remove laravel/framework v6.0.4
- Conclusion: don't install laravel/framework v6.0.4

**Comment by mckenziearts** [comment]
Hi this package don't actually support Laravel 6. I'll fix that really soon

**Comment by olipiskandar** [comment]
nice.. cant wait for this package 👍

**Comment by olipiskandar** [comment]
hello.. still not work..
after change to ^1.1
